### PR TITLE
Create docker mkdocs image

### LINKED ISSUE #1: Create docker image for running MkDocs
### Overview

We need an initial pass at a docker image for MkDocs so that developers can run MkDocs without installing it on their own computers. The idea is that devs from any HfLA project shouldn't need to know python in order to edit and preview MkDocs documentation locally.

### Action Items

- [x] research hfla projects using MkDocs
- [x] create docker image containing MkDocs and common plugins used by projects
- [x] create gha to build and push the image to dockerhub
- [x] create documentation on how to use the image
- [x] create docs on how to extend the image
- [x] create docs on how to update the image

### Resources/Instructions
- [dive](https://github.com/wagoodman/dive) tool for examining docker image layers and contents

### PR DESCRIPTION
**Pull request by fyliu**
- uses an alpine image with a recent python version.
- uses cache mounts to increase rebuild speed and reduce image size.
- uses poetry to manage dependencies.
- gha generates project documentation on code push.
- LICENSE and README file are being imported into the docs.
- gha builds and uploads docker images on code push.
- uses multiplatform builds to support regular PCs (amd64) as well as those with Apple silicon (arm64).

Closes #1

### CODE REVIEW

**Comment by fyliu** [comment]
This was developed from my fork where the GHAs point to my account, which is "fyliu" for both github and docker. The hackforla docker account is "hackforlaops". I hope I made changes to all the places. I did a grep and didn't find "fyliu" anywhere.

[Link to my docker repo fyliu/mkdocs](https://hub.docker.com/r/fyliu/mkdocs/tags)
[Link to hackforla's docker repo hackforlaops/mkdocs](https://hub.docker.com/r/hackforlaops/mkdocs/tags)

### Docker credentials for CI

I set the docker token and password in hackforla and they should be correct, although I haven't tested the one for the hackforla repo. I did test the credentials from my local machine to upload the mkdocs:testing image and that worked.

**Comment by vraer** [comment]
@fyliu, the container spun up smoothly with docker-compose and everything's running as it should. 👍 

The GHA workflows also seem to be in order. I can't access the repo settings to check the secrets though. Anything else you need me to look into?

**Comment by fyliu** [comment]
I think it's fine as long as the docker part works. Thanks @vraer!

**Review by vraer — APPROVED** [review]

**Comment by vraer** [comment]
Approved! Good work @fyliu

**Pull request merged**
